name: CI - Playwright Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Strapi server in background
        run: npm start &

      - name: Wait for Strapi to be ready
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: http://localhost:1337/admin
          timeout: 360

      - name: Run Playwright tests
        run: npx playwright test
